_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 12.577457427978516
  - 55.68825417763473
  - 15
description: 'A clean, fresh map style emphasizing  tasteful textures, natural building shadows and the soft, warm glow of the sun. '
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1393295698671
name: Vetiver
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
template: ''
