_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -122.43329286575317
  - 37.80440977021365
  - 16
description: 'A clean, fresh map style emphasizing  tasteful textures, natural building shadows and the soft, warm glow of the sun. '
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1393266092058
name: Vetiver
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
template: ''
